### ISSUE TITLE
new url unavailable without logging in?

### ISSUE THREAD

**Issue by karlp** [MorgothCreator/XMEGA_CORE_IP_V2#1]
The new url provided as new home: https://git.morgothdisk.com/ is unavailable without logging in.  Was that the intention?  This github project is nicely accessible.

**Comment by MorgothCreator** [comment]
All projects are under: https://git.morgothdisk.com/explore/projects

**Comment by karlp** [comment]
That's true, but that's not the url you're promoting.  It looks like this at present, is that really the intention?
![screenshot from 2018-08-23 20-13-07](https://user-images.githubusercontent.com/127907/44549586-0f6ec380-a711-11e8-9590-37d543ad0c53.png)

**Comment by karlp** [comment]
nvm, I see you've udpated teh readme .)
